### ISSUE TITLE
Make capacity power of Two check constant for ConstGenericRingBuffer

### ISSUE THREAD

**Issue by zimward** [NULLx76/ringbuffer#61]
Since the capacity of the ConstGenericRingBuffer is known at compile-time the check can be performed there.This is currently only possible with rust-nightly. Therefore i would suggest leaving this issue open until [generic_const_exprs](https://github.com/rust-lang/rust/issues/76560) has been stabilized.
I already implemented this using the current version of rust nightly. See #62

**Comment by Sjord** [comment]
It seems that the capacity must be a power of two, for this trick in [mask](https://github.com/NULLx76/ringbuffer/blob/master/src/lib.rs#L80-L82) to work:

```
const fn mask(cap: usize, index: usize) -> usize {
    index & (cap - 1)
}
```

This basically does `index = index % cap`. It's faster than that, but only works if cap is a power of two.

If it's possible to detect whether `cap` is a power of two at compile time, it would also be possible to change the implementation of `mask`: use the fast bitwise AND when cap is a power of two, and use the slow modulo operation when it's not.

Of course the compiler also knows about this trick. The modulo operation will be optimized to a bitwise operation when the capacity is a power of two. So `index % cap` gives optimal performance, while also supporting capacities that are not a power of two. And it doesn't need an explicit compile time check.

For `AllocRingBuffer` the capacity is not known at compile time, and that would become significantly slower when using `index % cap`. Maybe it would it be possible to pick the masking function when the `AllocRingBuffer` is initialized.

I think it would be nice if the ringbuffers support arbitrary capacity, instead of just powers of two.
