### ISSUE TITLE
ConstGenericRingBuffer does not work with link_section?

### ISSUE THREAD

**Issue by Jonarw** [NULLx76/ringbuffer#77]
I am using `ringbuffer` in my STM32 project (so no_std). I have a static `ConstGenericRingBuffer` declared like this:

```
#[link_section = ".axisram"]
static mut BUFFER: ConstGenericRingBuffer<SomeStruct, 256> = ConstGenericRingBuffer::new();
```

I would like to have the ringbuffer in AXISRAM, as DTCM (where my stack lives) would not fit this buffer.
This does not work. The moment I try to access the buffer, the code panics and inspecting the `BUFFER` object reveals that the readptr and writeptr have non-sensical values (outside of the range of my device's memory).
However, the address of `BUFFER` in memory is correctly shown as `0x24000000` (AXISRAM on STM32H743) by the debugger.

I tried changing the above code to:
```
static mut BUFFER: ConstGenericRingBuffer<SomeStruct, 8> = ConstGenericRingBuffer::new();
```
So I removed the `link_section` attribute and reduced the size of the buffer so it fits in DTCM.
Then it works perfectly (apart from the buffer being shorter than I'd like).

Is this expected? Am I doing something wrong? Can I make this work somehow?

**Comment by jonay2000** [comment]
This is an interesting problem. In theory, the values of readptr and writeptr are initialized to zero as you can see in the image below. That should make sure that that your issue is impossible
![image](https://user-images.githubusercontent.com/22172241/229240843-60673575-7599-4de3-9ec0-fb7164fecba2.png)

This code seems correct and it means that something is going wrong in your setup and unrelated to ringbuffer.

Having said that, I do have a theory about what's going wrong here. The initialized version of a ringbuffer *could* be a contiguous region of zero bytes. The MaybeUninit is alowed to be zeros, and the pointers are even explicitly set to zero.

I think the compiler is allowed to assume that some parts of memory are filled by zeros at startup. For example, the bss section where static variables are usually placed. 

It could be that the compiler realizes that a zero pattern is a totally valid initialization for a ringbuffer, assumes that the buffer is placed in zeroed memory, and thus doesn't *actually* generate the code that sets the pointer fields to zero. They're zeroed already anyway.

However, I'm not entirely sure that your `.axisram` section *has* this guarantee. Is your runtime startup zeroing it? If not, should it?

For example, `cortex_m_rt` explicitly zeroes the bss section here before executing the program entry point https://docs.rs/cortex-m-rt/latest/src/cortex_m_rt/lib.rs.html#532

I could be wrong about this, it's only a theory. However, our ringbuffer code *seems* correct. If you manage to solve this and prove me wrong, I'm happy to hear!

**Comment by Jonarw** [comment]
Thanks for your assessment!
It seems to me that something along these lines is probably what's going on here.
I tried again with the `ConstGenericRingBuffer` in AXISRAM, and manually set `writeptr` and `readptr` to `0` via the debugger. Then everything worked just fine.

This seems to indicate indeed that ringbuffer is most likely not to blame here. In that sense this particular issue is kind of resolved.

Of course I would still like to find out who or what is actually to blame here (and of course a legitimate answer could be: myself). 

The relevant section of my memory.x used to look like this:

```
  .axisram (NOLOAD) : ALIGN(8) {
    *(.axisram .axisram.*);
    . = ALIGN(8);
    } > AXISRAM
```

As far as I understand, the `(NOLOAD)` indicates that this memory region does not need to be intialized, which sound exactly like my problem. So I removed the `(NOLOAD)` and tried again, but with the same result.

So I guess I need to either:
- Make sure AXISRAM is intialized before using it
- Tell the compiler it shouldn't assume AXISRAM is intialized

The second option is probably preferable. Any tips how I could achieve that?

**Comment by jonay2000** [comment]
you could manually do it at startup, like cortex-m-rt does. Alternatively, you can define the `_sbss` variables in the linker script if you don't have another bss section so cortex-m-rt does it for you. 

I'll be closing this issue now, but I'd still be interested to hear what you did to solve it
